In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("C:/Users/Ines/Downloads/usgs_files/data/clean_data/usgs_mrds_clean.csv")

C:\Users\Ines\AppData\Local\Temp\ipykernel_16272\2885693157.py:1: DtypeWarning: Columns (5,6,8,79) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:/Users/Ines/Downloads/usgs_files/data/clean_data/usgs_mrds_clean.csv")

In [4]:
df.head()

,county,dep type left,geometry,index right,gid,mineral,dep type right,Unnamed: 9,dep type,country,...,is_EU_CRM_present,is_US_CRM_present,is_Canada_CRM_present,is_AUS_CRM_present,all applications,application,data source,data source url,data source year,region_clean
0,Eagle,NaN,POINT (-106.20061 39.69999),NaN,NaN,NaN,NaN,NaN,NaN,United States of America,...,False,False,True,False,NaN,NaN,USGS Mineral Resources Data System,https://mrdata.usgs.gov/mrds/,2011.0,NaN
1,Utah,NaN,POINT (-111.6003 40.29026),NaN,NaN,NaN,NaN,NaN,NaN,United States of America,...,False,False,False,False,"Nuclear Energy, Solar Pv, Electricity Grid, ...",Nuclear energy,USGS Mineral Resources Data System,https://mrdata.usgs.gov/mrds/,2011.0,NaN
2,Park,Placer,POINT (-110.78471 45.09213),NaN,NaN,NaN,NaN,NaN,NaN,United States of America,...,False,False,False,False,"Aircraft (Fighter, Transport, Maritime Patro...",NaN,USGS Mineral Resources Data System,https://mrdata.usgs.gov/mrds/,2011.0,NaN
3,Amador,NaN,POINT (-120.72045 38.31935),NaN,NaN,NaN,NaN,NaN,NaN,United States of America,...,False,False,False,False,"Aircraft (Fighter, Transport, Maritime Patro...",NaN,USGS Mineral Resources Data System,https://mrdata.usgs.gov/mrds/,2011.0,NaN
4,Calaveras,NaN,POINT (-120.68045 38.15324),NaN,NaN,NaN,NaN,NaN,NaN,United States of America,...,False,False,False,False,"Aircraft (Fighter, Transport, Maritime Patro...",NaN,USGS Mineral Resources Data System,https://mrdata.usgs.gov/mrds/,2011.0,NaN

In [6]:
df.columns

Index(['county', 'dep type left', 'geometry', 'index right', 'gid', 'mineral',
       'dep type right', 'Unnamed: 9', 'dep type', 'country', 'region',
       'region clean', 'year', 'latitude', 'longitude', 'site name', 'state',
       'dev stat', 'oper type', 'all commodities mrds', 'all commodities gdcm',
       'bismuth', 'borates', 'magnesium', 'phosphorus', 'scandium',
       'silicon metal', 'tungsten', 'strontium', 'iridium', 'platinum',
       'palladium', 'rhodium', 'ruthenium', 'osmium', 'uranium', 'molybdenum',
       'chromium', 'silver', 'aluminum', 'nickel', 'iron', 'selenium', 'zinc',
       'cadmium', 'copper', 'lead', 'gold', 'antimony', 'baryte', 'beryllium',
       'cobalt', 'fluorspar', 'gallium', 'germanium', 'hafnium', 'indium',
       'lithium', 'natural graphite', 'niobium', 'tantalum', 'titanium',
       'vanadium', 'pge', 'pgm', 'manganese', 'tin', 'zirconium', 'tellurium',
       'all commodities', 'is_EU_CRM_present', 'is_US_CRM_present',
       'is_Canada_CRM_present', 'is_AUS_CRM_present', 'all applications',
       'application', 'data source', 'data source url', 'data source year',
       'region_clean'],
      dtype='object')

In [14]:
#print the country and region clean for when country == solomon islands
df.loc[df['region clean'] == 'Caribbean', ['country', 'region clean']]

                          country region clean
6683     United States of America    Caribbean
14808                     Jamaica    Caribbean
14928    United States of America    Caribbean
15244    United States of America    Caribbean
15245    United States of America    Caribbean
...                           ...          ...
1681698                      Cuba    Caribbean
1681699                      Cuba    Caribbean
1681700                      Cuba    Caribbean
1681701                      Cuba    Caribbean
1681702                      Cuba    Caribbean

[12540 rows x 2 columns]